project:
  type: website

website:
  title: "Obesity Risk â€“ Exploratory Analysis"
  favicon: favicon.ico
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - analysis/test1.qmd
      - analysis/test2.qmd
      - analysis/test3.qmd
      - analysis/test4.qmd
      - analysis/test5.qmd
      - analysis/test6.qmd
  
  page-footer: 
    left: "Copyright 2026, Jaime V." 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/  



format:
  html:
    theme: cosmo
    toc: true