project:
  type: website

website:
  title: "Obesity Risk â€“ Exploratory Analysis"
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - analysis/imc.qmd
      - analysis/activity.qmd
      - analysis/diet.qmd

format:
  html:
    theme: cosmo
    toc: true