project:
  type: website

website:
  title: "Obesity Risk â€“ Exploratory Analysis"
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - analysis/test1.qmd
      - analysis/test2.qmd
      - analysis/test3.qmd
      - analysis/test4.qmd
      - analysis/test5.qmd

format:
  html:
    theme: cosmo
    toc: true